[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc = "0.8.19"
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
monad_testnet = "https://rpc.testnet.monad.xyz"
monad_mainnet = "https://rpc.monad.xyz"

[etherscan]
monad_testnet = { key = "" }
monad_mainnet = { key = "" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options 