[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
monad_testnet = "https://rpc.testnet.monad.xyz"

[etherscan]
monad_testnet = { key = "" }

# For deployment
[profile.default.fuzz]
runs = 1000

[profile.default.invariant]
runs = 1000
depth = 15
fail_on_revert = false 